#include "embedded_font.hpp"

#include <cstdio>
#include <vector>

#if RENCM_FONT_COMPRESSED
#include <zlib.h>
#endif

#if defined(_MSC_VER)
// MSVC cannot assemble the GNU .S the other toolchains use, so on Windows the
// fonts are linked in as RCDATA resources instead (see CMakeLists.txt) and read
// back here with FindResource.
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#else
// Symbols are generated by CMake (see CMakeLists.txt -> embedded_font.S, one
// pair per entry in RENCM_FONTS). The explicit asm() names avoid the
// platform-specific leading underscore.
extern "C" {
extern const unsigned char rencm_font0_start[] asm("rencm_font0_start");
extern const unsigned char rencm_font0_end[] asm("rencm_font0_end");
extern const unsigned char rencm_font1_start[] asm("rencm_font1_start");
extern const unsigned char rencm_font1_end[] asm("rencm_font1_end");
extern const unsigned char rencm_font2_start[] asm("rencm_font2_start");
extern const unsigned char rencm_font2_end[] asm("rencm_font2_end");
}
#endif

namespace rencm::app {
namespace {

constexpr std::size_t kFontCount = 3;

struct Blob {
    const unsigned char* data;
    std::size_t size;
};

#if defined(_MSC_VER)
Blob stored(std::size_t index) {
    char name[32];
    std::snprintf(name, sizeof(name), "rencm_font%zu", index);
    const HRSRC res = ::FindResourceA(nullptr, name, RT_RCDATA);
    if (res == nullptr) return {nullptr, 0};
    const void* p = ::LockResource(::LoadResource(nullptr, res));
    return {static_cast<const unsigned char*>(p),
            static_cast<std::size_t>(::SizeofResource(nullptr, res))};
}
#else
Blob stored(std::size_t index) {
    switch (index) {
        case 0: return {rencm_font0_start, static_cast<std::size_t>(rencm_font0_end - rencm_font0_start)};
        case 1: return {rencm_font1_start, static_cast<std::size_t>(rencm_font1_end - rencm_font1_start)};
        case 2: return {rencm_font2_start, static_cast<std::size_t>(rencm_font2_end - rencm_font2_start)};
        default: return {nullptr, 0};
    }
}
#endif

#if RENCM_FONT_COMPRESSED
// Inflate a gzip stream. Returns an empty vector on failure.
std::vector<uint8_t> inflate_gzip(const unsigned char* in, std::size_t in_len) {
    z_stream s{};
    if (inflateInit2(&s, 16 + MAX_WBITS) != Z_OK) return {};

    s.next_in = const_cast<Bytef*>(reinterpret_cast<const Bytef*>(in));
    s.avail_in = static_cast<uInt>(in_len);

    std::vector<uint8_t> out(1u << 20);
    for (;;) {
        if (out.size() - s.total_out < (64u << 10)) out.resize(out.size() * 2);
        s.next_out = reinterpret_cast<Bytef*>(out.data() + s.total_out);
        s.avail_out = static_cast<uInt>(out.size() - s.total_out);

        const int rc = inflate(&s, Z_NO_FLUSH);
        if (rc == Z_STREAM_END) break;
        if (rc != Z_OK) {
            inflateEnd(&s);
            return {};
        }
    }
    out.resize(s.total_out);
    inflateEnd(&s);
    return out;
}
#endif

std::vector<uint8_t> load(std::size_t index) {
    const Blob b = stored(index);
#if RENCM_FONT_COMPRESSED
    return inflate_gzip(b.data, b.size);
#else
    return std::vector<uint8_t>(b.data, b.data + b.size);
#endif
}

// All faces decompressed once and kept for the atlas lifetime.
const std::vector<std::vector<uint8_t>>& all_blobs() {
    static const std::vector<std::vector<uint8_t>> blobs = [] {
        std::vector<std::vector<uint8_t>> v;
        v.reserve(kFontCount);
        for (std::size_t i = 0; i < kFontCount; ++i) v.push_back(load(i));
        return v;
    }();
    return blobs;
}

} // namespace

std::size_t embedded_font_count() { return kFontCount; }

const uint8_t* embedded_font_data(std::size_t index) {
    const auto& blobs = all_blobs();
    return index < blobs.size() ? blobs[index].data() : nullptr;
}

std::size_t embedded_font_size(std::size_t index) {
    const auto& blobs = all_blobs();
    return index < blobs.size() ? blobs[index].size() : 0;
}

std::size_t embedded_font_stored_size() {
    std::size_t total = 0;
    for (std::size_t i = 0; i < kFontCount; ++i) total += stored(i).size;
    return total;
}

} // namespace rencm::app
